app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {

	return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::resource('Club', 'ClubController');

app/Club.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
    protected $fillable = ['name', 'description'];

	public $timestamps = false;

	protected $table = 'clubs';
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClubController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Http\Controllers\Controller;

use App\Club;

class ClubController extends Controller
{
	public function index()
		{
			$clubs = Club::all();

			return view('clubs.index')->with('clubs', $clubs);
		}
	
	public function create()
		{
			return view('clubs.create');
		}

	public function store(Request $request)
		{
		/*	There are two ways to enter products into a table as below

			$product = new Product();

			$product->name = $request->name;
			$product->price = $request->price;
			$product->save();

			return "Something"; */

			$inputs = $request->all();
			$club = Club::Create($inputs);

			//return redirect()->route('Product.index');
		
			// THE ABOVE REDIRECT METHOD WE CAN ALSO WRITE AS BELOW.

			return redirect()->action('ClubController@index');
		
		}

		public function show($id)
			{
			
				$club = Club::find($id);

				// return $product;  here it prints in json code but we have to print in web page then 

				return view('clubs.show')->with('club', $club);
			}

		  public function destroy($id)
			{
			
				//Product::destroy($id);

				$club = Club::find($id)
								->delete();

				return redirect()->route('Club.index');
			} 

		public function edit($id)
			{
			
				$club = Club::find($id);

				// return view('products.edit')->with('product', $product);  OR

				return view('clubs.edit', compact('club', $club));
			}

		public function update(Request $request, $id)
			{
			
				$club = Club::find($id);

				$club->name = $request->name;
				$club->description = $request->description;

				$club->save();

				return redirect()->route('Club.index');
			}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

resources/views/clubs/create.blade.php
@extends('layouts.layoutclub')

@section('title')

	Create new Product

@stop

@section('body')

{!! Form::open(['route'=>'Club.store']) !!}

{!! Form::label('name', ' Club Name') !!}

{!! Form::text('name', null, ['placeholder'=> "Give club name"]) !!}

</br>

{!! Form::label('description', 'Description') !!}

{!! Form::text('description', null, ['placeholder'=> "Give description"]) !!}

{!! Form::submit('Create') !!}

{!! Form::close() !!}

@stop

resources/views/clubs/edit.blade.php
@extends('layouts.layoutclub')

@section('title')

 Edit	{{ $club->name }}

@stop

@section('body')

{!! Form::model( $club, [

		'method'=>'patch',
		'route'=>['Club.update', $club->id]
		
		]) !!}

{!! Form::label('name', 'Name') !!}
{!! Form::text('name', $club->name, ['placeholder'=>"Give a name"]) !!}

</br>

{!! Form::label('description', 'Description') !!}
{!! Form::text('description', $club->description, ['placeholder'=>"Give a description"]) !!}


{!! Form::submit('Edit') !!}

{!! Form::close() !!}

@stop

resources/views/clubs/index.blade.php
@extends('layouts.layoutclub')

@section('title')
	
	All clubs

@stop

@section('body')

@foreach($clubs as $club)
	
	<h1> {{ $club->name}}</h1>
	<h3> {{ $club->description}}</h3>
	</br>

@endforeach

@stop

resources/views/clubs/show.blade.php
@extends('layouts.layoutclub')

@section('title')

	{{ $club->name }}

@stop

@section('body')

{!! Form::open([

		'method'=>'delete',
		'route'=>['Club.destroy', $club->id]
		
		]) !!}

<h1> {{ $club->name }} </h1>

<h3> {{ $club->description }} </h3>

<a href="{{route('Club.edit', $club->id)}}"> Edit </a> 

{!! Form::submit('Delete') !!}

{!! Form::close() !!}

@stop

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/layoutclub.blade.php
<!DOCTYPE html>

<html>
<head> 
			<title>@yield('title')</title>
</head>

<body>
	
	@include('layouts.menuclub')
	
	@yield('body')

	{{-- This comment will not be in the rendered HTML --}}

</body>

</html>

resources/views/layouts/menuclub.blade.php
<h1>

		Club database

</h1>

resources/views/login.blade.php
<!-- resources/views/auth/login.blade.php -->

<form method="POST" action="/auth/login">
    {!! csrf_field() !!}

    <div>
        Email
        <input type="email" name="email" value="{{ old('email') }}">
    </div>

    <div>
        Password
        <input type="password" name="password" id="password">
    </div>

    <div>
        <input type="checkbox" name="remember"> Remember Me
    </div>

    <div>
        <button type="submit">Login</button>
    </div>
</form>

resources/views/register.blade.php
<!-- resources/views/auth/register.blade.php -->

<form method="POST" action="/auth/register">
    {!! csrf_field() !!}

    <div>
        Name
        <input type="text" name="name" value="{{ old('name') }}">
    </div>

    <div>
        Email
        <input type="email" name="email" value="{{ old('email') }}">
    </div>

    <div>
        Password
        <input type="password" name="password">
    </div>

    <div>
        Confirm Password
        <input type="password" name="password_confirmation">
    </div>

    <div>
        <button type="submit">Register</button>
    </div>
</form>